apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  # postgres
  DATABASE_DIRECTORY: "${DATABASE_DIRECTORY}"
  DB_NAME: "${DB_NAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_USER: "${DB_USER}"
  POSTGRES_DB: "${POSTGRES_DB}"
  POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  POSTGRES_USER: "${POSTGRES_USER}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hapi-config
data:
  # hapi
  DB_HOST: "${DB_HOST}"
  DB_NAME: "${DB_NAME}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_PORT: "${DB_PORT}"
  DB_SCHEMA: "${DB_SCHEMA}"
  DB_USER: "${DB_USER}"
  EOS_API_ENDPOINT: "${EOS_API_ENDPOINT}"
  VIRTUAL_HOST: "${VIRTUAL_HOST}"
  VIRTUAL_PORT: "${VIRTUAL_PORT}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hasura-config
data:
  # hasura
  HASURA_GRAPHQL_DATABASE_URL: "${HASURA_GRAPHQL_DATABASE_URL}"
  HASURA_GRAPHQL_MIGRATIONS_DIR: "${HASURA_GRAPHQL_MIGRATIONS_DIR}"
  MIGRATION_DIRECTORY: "${MIGRATION_DIRECTORY}"
  HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
  HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
