apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: demux
  name: demux
spec:
  replicas: 1
  selector:
    matchLabels:
      service: demux
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network/default: "true"
        service: demux
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: eosrate
        - name: DB_PASSWORD
          value: pass
        - name: DB_PORT
          value: "5432"
        - name: DB_SCHEMA
          value: public
        - name: DB_USER
          value: user
        - name: EOS_API_ENDPOINT
          value: https://bp.cryptolions.io
        - name: WAIT_HOSTS
          value: postgres:5432, hasura:8088
        - name: WAIT_HOSTS_TIMEOUT
          value: "60"
        image: eoscostarica506/demux
        imagePullPolicy: "Always"
        name: eosrate-demux
        ports:
        - containerPort: 3030
      restartPolicy: Always
