apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: hasura
  name: hasura
spec:
  replicas: 1
  selector:
    matchLabels:
      service: hasura
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        network: "true"
        service: hasura
    spec:
      containers:
      - args:
        - graphql-engine
        - serve
        - --enable-console
        env:
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: HASURA_GRAPHQL_ADMIN_SECRET
        - name: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
          valueFrom:
            secretKeyRef:
              name: hasura-secret
              key: HASURA_GRAPHQL_UNAUTHORIZED_ROLE
        envFrom:
        - configMapRef:
            name: hasura-config
        image: hasura/graphql-engine:v1.2.0-beta.4.cli-migrations
        imagePullPolicy: "Always"
        name: eosrate-hasura
        ports:
        - containerPort: 8088
      restartPolicy: Always
