apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: pgweb
  name: pgweb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: pgweb
  template:
    metadata:
      labels:
        network: "true"
        service: pgweb
    spec:
      containers:
      - env:
        - name: DATABASE_URL
          value: postgres://user:pass@postgres:5432/eosrate?sslmode=disable
        image: sosedoff/pgweb:latest
        imagePullPolicy: "Always"
        name: eosrate-pgweb
        ports:
        - containerPort: 8081
      restartPolicy: Always
